// Copyright Ludens Studio. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace ArenaGameplayTags
{
	ARENA_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LookMouse);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Drop);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);

	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);
	
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_Grenade_AOE);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_Grenade_DirectHit);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageType_Grenade_Effect);

	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Grenade_Duration_Message);
	ARENA_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Duration_Message);
}
